-- ============================================================================
-- 00024_healing_paths_seed.sql
--
-- Seed content for the two initial healing paths:
--   * Weg 1: Reinheit — 40 Tage (slug: reinheit-40-tage, theme: pornografie)
--   * Weg 2: Aufbruch — 20 Tage (slug: aufbruch-20-tage, theme: acedia)
--
-- Idempotent: all inserts use ON CONFLICT ... DO UPDATE so this seed can be
-- re-run safely via the Supabase SQL editor to refresh content.
--
-- The "Tagesgrundlage (in Ora Mundi)" block from the source markdown is NOT
-- stored here — the UI renders a fixed TagesgrundlageCard component per day.
-- prayer_refs is kept as an empty JSONB array for the same reason.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Weg 1: Reinheit — 40 Tage
-- ---------------------------------------------------------------------------

insert into healing_programs (
  slug, theme, duration_days, title_de, title_en,
  subtitle_de, intro_de, scripture_motto, closing_de,
  requires_confessor, show_seelengemeinschaft, icon, is_published
) values (
  'reinheit-40-tage',
  'pornografie',
  40,
  'Reinheit',
  'Purity',
  '40 Tage aus der Gefangenschaft der Pornografie',
  E'Pornografie verwundet die Seele, verzerrt das Bild des Menschen als Gottes Ebenbild und bindet den Willen. Dieser Weg ist kein Willensprogramm, sondern ein Gebetsweg. Christus allein befreit.\n\nEmpfohlene Begleitung:\n- Regelmäßige Beichte (mindestens einmal in diesen 40 Tagen, idealerweise zu Beginn)\n- Ein geistlicher Begleiter oder Beichtvater\n- Technische Schutzmaßnahmen (Filter, Accountability-Software) — der Wille allein reicht nicht\n- Tägliches Gebet zur festen Uhrzeit\n\nWenn du fällst: Steh auf. Der Weg geht weiter. Gottes Barmherzigkeit ist größer als jede Sünde.',
  E'Mt 5,8 — "Selig, die reinen Herzens sind, denn sie werden Gott schauen."',
  E'Ab Tag 41:\n- Tägliches Gebet zur festen Zeit (auch 5 Minuten reichen).\n- Monatliche Beichte als Rhythmus.\n- Wöchentliche Eucharistie — mindestens sonntags.\n- Jährlich einmal die 40 Tage wiederholen oder eine geistliche Exerzitienzeit.\n- Bei Fall: sofort zur Beichte, nicht zögern. Der Weg ist nie verloren.',
  true,
  true,
  'favorite',
  true
)
on conflict (slug) do update set
  theme = excluded.theme,
  duration_days = excluded.duration_days,
  title_de = excluded.title_de,
  title_en = excluded.title_en,
  subtitle_de = excluded.subtitle_de,
  intro_de = excluded.intro_de,
  scripture_motto = excluded.scripture_motto,
  closing_de = excluded.closing_de,
  requires_confessor = excluded.requires_confessor,
  show_seelengemeinschaft = excluded.show_seelengemeinschaft,
  icon = excluded.icon,
  is_published = excluded.is_published,
  updated_at = now();

-- Days 1-40 for Weg 1
with program as (select id from healing_programs where slug = 'reinheit-40-tage')
insert into healing_program_days (
  program_id, day_number, scripture_ref, scripture_de,
  reflection_de, prayer_de, action_de, prayer_refs
) values
  ((select id from program), 1,
    'Mt 4,1-2',
    E'Dann wurde Jesus vom Geist in die Wüste geführt, um vom Teufel versucht zu werden. Als er vierzig Tage und vierzig Nächte gefastet hatte, hungerte ihn.',
    E'Jesus selbst ging in die Wüste — nicht weil er sündig war, sondern um uns den Weg zu zeigen. Deine 40 Tage beginnen heute. Die Wüste ist der Ort, an dem das Wesentliche sichtbar wird.',
    E'Herr Jesus Christus, du bist in die Wüste gegangen, um zu kämpfen und zu siegen. Führe auch mich heute in die Wüste meines Herzens. Ich vertraue nicht auf meine Kraft, sondern auf deine. Amen.',
    E'Schreibe auf einen Zettel: "Ab heute gehöre ich Christus." Trage ihn 40 Tage bei dir.',
    '[]'::jsonb),
  ((select id from program), 2,
    '1 Joh 1,9',
    E'Wenn wir unsere Sünden bekennen, ist er treu und gerecht, sodass er uns die Sünden vergibt und uns von allem Unrecht reinigt.',
    E'Scham bindet. Bekenntnis befreit. Pornografie lebt vom Verborgenen.',
    E'Vater, ich bekenne dir, was ich getan habe. Ich schäme mich. Doch ich komme zu dir, weil du treu bist. Reinige mich. Amen.',
    E'Plane einen Beichttermin in den nächsten 7 Tagen. Schreibe Ort und Uhrzeit in den Kalender.',
    '[]'::jsonb),
  ((select id from program), 3,
    'Mt 5,28-29',
    E'Wer eine Frau auch nur lüstern ansieht, hat in seinem Herzen schon Ehebruch mit ihr begangen. Wenn dich dein rechtes Auge zum Bösen verführt, dann reiß es aus und wirf es weg!',
    E'Der Blick ist die Eingangstür. Wer die Tür schließt, verhindert den Einbruch.',
    E'Herr, heilige meine Augen. Lass mich sehen, was du siehst — die Würde jedes Menschen. Amen.',
    E'Entferne heute eine konkrete Quelle — ein Bookmark, eine App, ein Konto. Jetzt, nicht morgen.',
    '[]'::jsonb),
  ((select id from program), 4,
    'Jes 43,1',
    E'Fürchte dich nicht, denn ich habe dich ausgelöst, ich habe dich beim Namen gerufen, du gehörst mir.',
    E'Du bist nicht deine Sünde. Du bist getauft. Dein Name ist in den Himmel geschrieben.',
    E'Vater, du kennst meinen Namen. Du hast mich bei der Taufe angenommen. Ich gehöre dir — nicht der Sünde. Amen.',
    E'Erinnere dich heute dreimal an dein Taufdatum. Falls unbekannt: frage im Pfarramt nach.',
    '[]'::jsonb),
  ((select id from program), 5,
    'Ps 101,3',
    E'Nie stelle ich Nichtiges vor meine Augen. Ich hasse das Tun der Treulosen, es soll mich nicht berühren.',
    E'Was wir nicht ansehen, verliert Macht über uns. Fasten ist nicht Strafe, sondern Freiheit.',
    E'Herr, ich faste heute mit meinen Augen. Jeder Blick, den ich dir gebe, sei ein kleines Opfer. Amen.',
    E'Social Media heute: maximal 10 Minuten. Timer stellen.',
    '[]'::jsonb),
  ((select id from program), 6,
    'Ps 51,12',
    E'Erschaffe mir, Gott, ein reines Herz und gib mir einen neuen, beständigen Geist!',
    E'Nur Gott erschafft ein reines Herz — du kannst es nicht selbst machen. Bitte darum.',
    E'(Betrachte heute den ganzen Psalm 51 langsam — der Bußpsalm Davids nach seinem Fall.)',
    E'Lies Psalm 51 laut vor. Einmal morgens, einmal abends.',
    '[]'::jsonb),
  ((select id from program), 7,
    'Gen 2,3',
    E'Und Gott segnete den siebten Tag und heiligte ihn.',
    E'Eine Woche ist vorbei. Gott ruht am siebten Tag. Auch dein Kampf darf heute in seiner Ruhe stehen.',
    E'Herr, ich danke dir für diese erste Woche. Was gut war, kam von dir. Was schwer war, trug ich nicht allein. Amen.',
    E'Gehe heute zur Heiligen Messe (falls Sonntag) oder besuche eine Kirche für 15 Minuten stilles Gebet.',
    '[]'::jsonb),
  ((select id from program), 8,
    'Lk 1,28',
    E'Sei gegrüßt, du Begnadete, der Herr ist mit dir.',
    E'Maria ist die Unbefleckte. Wer sich ihr anvertraut, findet Zuflucht vor jeder unreinen Versuchung.',
    E'Maria, Mutter der Reinen, nimm mich unter deinen Mantel. Wo du bist, kann der Feind nicht hin. Amen.',
    E'Bete heute ein Gesätz Rosenkranz (10 Ave Maria).',
    '[]'::jsonb),
  ((select id from program), 9,
    '1 Kor 6,19-20',
    E'Wisst ihr nicht, dass euer Leib ein Tempel des Heiligen Geistes ist, der in euch wohnt? Ihr gehört nicht euch selbst; denn um einen teuren Preis seid ihr erkauft worden. Verherrlicht also Gott in eurem Leib!',
    E'Dein Körper ist nicht Mittel zum Lustgewinn. Er ist Wohnung Gottes.',
    E'Heiliger Geist, wohne in mir. Mein Leib gehört dir. Heilige, was verwundet ist. Amen.',
    E'Bewege dich heute 30 Minuten — Spaziergang, Sport. Körper als Tempel ehren.',
    '[]'::jsonb),
  ((select id from program), 10,
    'Joh 20,27',
    E'Strecke deinen Finger hierher aus und sieh meine Hände! Streck deine Hand aus und leg sie in meine Seite!',
    E'Thomas musste die Wunden Christi berühren, um zu glauben. Auch du darfst deine Wunden sehen — und sie in seine legen.',
    E'Herr, ich zeige dir heute die Wunde, aus der meine Sucht kommt. Heile, was ich nicht heilen kann. Amen.',
    E'Schreibe heute stichpunktartig auf: Wann hat es angefangen? Was löst es aus? (Nur für dich und ggf. den Beichtvater.)',
    '[]'::jsonb),
  ((select id from program), 11,
    'Eph 6,12',
    E'Denn wir haben nicht gegen Menschen aus Fleisch und Blut zu kämpfen, sondern gegen die Mächte und Gewalten, gegen die Weltherrscher dieser Finsternis.',
    E'Pornografie ist nicht nur Schwäche — sie ist ein geistlicher Kampf. Der Feind ist real, aber besiegt.',
    E'Im Namen Jesu Christi widerstehe ich dir, Satan. Weiche von mir. Christus ist mein Herr. Amen.',
    E'Bete heute das Michaelsgebet ("Heiliger Erzengel Michael, verteidige uns im Kampfe…").',
    '[]'::jsonb),
  ((select id from program), 12,
    'Joh 6,56',
    E'Wer mein Fleisch isst und mein Blut trinkt, der bleibt in mir, und ich bleibe in ihm.',
    E'Die heilige Kommunion ist die stärkste Medizin gegen jede Unreinheit — wenn sie im Stand der Gnade empfangen wird.',
    E'Herr Jesus, im Heiligsten Sakrament ganz gegenwärtig, komm in mich. Reinige, was in mir unrein ist. Amen.',
    E'Wenn möglich, gehe heute zur Werktagsmesse. Sonst: eucharistische Anbetung für 15 Minuten.',
    '[]'::jsonb),
  ((select id from program), 13,
    'Mt 6,6',
    E'Wenn du beten willst, geh in deine Kammer, schließ die Tür zu; dann bete zu deinem Vater, der im Verborgenen ist.',
    E'Die Wüstenväter nannten die Unkeuschheit einen der acht Hauptgedanken. Ihre Waffe: das Jesusgebet — kurz, wiederholt, im Herzen.',
    E'"Herr Jesus Christus, Sohn Gottes, erbarme dich meiner." (50 Mal, langsam, auf den Atem.)',
    E'10 Minuten Jesusgebet heute. Ohne Handy, ohne Ablenkung.',
    '[]'::jsonb),
  ((select id from program), 14,
    'Phil 1,6',
    E'Ich vertraue darauf, dass er, der bei euch das gute Werk begonnen hat, es auch vollenden wird bis zum Tag Christi Jesu.',
    E'Zwei Wochen. Gott vollendet, was er begonnen hat. Du musst es nicht zu Ende bringen — er tut es.',
    E'Vater, du hast begonnen. Vollende. Ich vertraue dir. Amen.',
    E'Schreibe drei Dinge auf, die sich in zwei Wochen verändert haben.',
    '[]'::jsonb),
  ((select id from program), 15,
    'Gen 2,18',
    E'Es ist nicht gut, dass der Mensch allein ist.',
    E'Pornografie ist oft Ersatz für echte Nähe. Die Heilung geschieht in echter Gemeinschaft — mit Gott und Menschen.',
    E'Herr, du hast uns füreinander geschaffen. Führe mir Menschen zu, die mich wahrhaft lieben. Amen.',
    E'Rufe heute einen Freund oder Familienmitglied an. Kein Chat — ein Gespräch.',
    '[]'::jsonb),
  ((select id from program), 16,
    'Phil 4,8',
    E'Was immer wahrhaft, edel, gerecht, rein, liebenswert, ansprechend ist, was Tugend heißt und lobenswert ist, darauf seid bedacht!',
    E'Gedanken sind keine Sünde. Aber wir entscheiden, welchem Gedanken wir folgen.',
    E'Heiliger Geist, lehre mich unterscheiden: welcher Gedanke von dir kommt, welcher nicht. Amen.',
    E'Heute jeden unreinen Gedanken bewusst entlassen — mit dem Stoßgebet: "Jesus, Maria, Josef."',
    '[]'::jsonb),
  ((select id from program), 17,
    'Mk 9,29',
    E'Diese Art kann nur durch Gebet ausgetrieben werden.\n(In manchen Handschriften: "durch Gebet und Fasten".)',
    E'Der Leib muss lernen, nicht jeder Regung zu folgen. Fasten übt diesen Gehorsam.',
    E'Herr, ich faste heute aus Liebe zu dir. Jede Entbehrung sei ein Gebet. Amen.',
    E'Wähle heute ein konkretes Fasten: keine Süßigkeiten, keine Zwischenmahlzeiten, kein Kaffee — eines davon.',
    '[]'::jsonb),
  ((select id from program), 18,
    'Joh 8,11',
    E'Auch ich verurteile dich nicht. Geh und sündige von jetzt an nicht mehr!',
    E'Christus verurteilt nicht. Aber er sendet auch nicht in die Sünde zurück. Beide Worte gehören zusammen.',
    E'Herr, ich höre beide Worte heute. Du verurteilst mich nicht. Und du rufst mich weiter. Amen.',
    E'Schreibe den Vers auf und lege ihn dorthin, wo du oft hinschaust.',
    '[]'::jsonb),
  ((select id from program), 19,
    'Mt 1,19',
    E'Joseph, ihr Mann, der gerecht war…',
    E'Joseph ist das Vorbild des keuschen Mannes. Er schweigt, er schützt, er dient.',
    E'Heiliger Joseph, Schützer der Jungfrau, beschütze auch mich. Lehre mich Keuschheit, wie du sie gelebt hast. Amen.',
    E'Bete heute die Litanei vom heiligen Joseph oder das Gebet Papst Leos XIII. zum hl. Josef.',
    '[]'::jsonb),
  ((select id from program), 20,
    '2 Kor 4,16',
    E'Darum werden wir nicht müde; wenn auch unser äußerer Mensch aufgerieben wird, der innere wird Tag für Tag erneuert.',
    E'Die Hälfte ist geschafft. Der innere Mensch wird täglich erneuert — auch wenn der äußere müde ist.',
    E'Herr, danke für 20 Tage. Erneuere mich innerlich. Gib mir Kraft für die zweiten 20. Amen.',
    E'Gehe heute zur Beichte — falls nicht in den ersten 20 Tagen geschehen.',
    '[]'::jsonb),
  ((select id from program), 21,
    'Lk 9,23',
    E'Wer mein Jünger sein will, der verleugne sich selbst, nehme täglich sein Kreuz auf sich und folge mir nach.',
    E'Das Kreuz ist nicht das Problem — das Kreuz ist der Weg.',
    E'Herr, ich nehme heute mein Kreuz auf. Die Versuchung ist Teil davon. Ich trage es mit dir. Amen.',
    E'Trage heute bewusst ein Kreuzzeichen bei dir oder mache morgens und abends ein langsames Kreuzzeichen.',
    '[]'::jsonb),
  ((select id from program), 22,
    'Ps 103,12',
    E'So weit der Aufgang entfernt ist vom Untergang, so weit entfernt er von uns unsere Schuld.',
    E'Gott vergibt nicht halb. Er vergibt ganz. Was er vergeben hat, darfst du nicht mehr hervorholen.',
    E'Vater, ich empfange heute deine Vergebung. Ich lasse die Schuld los. Sie ist weit weg. Amen.',
    E'Nenne alte Sünden heute beim Namen — und sag laut: "Ist vergeben. Ist weg."',
    '[]'::jsonb),
  ((select id from program), 23,
    'Mt 6,14',
    E'Wenn ihr den Menschen ihre Verfehlungen vergebt, dann wird euer himmlischer Vater auch euch vergeben.',
    E'Manchmal steht eine alte Wunde im Weg — jemand, der dich verletzt hat. Vergeben heißt nicht vergessen. Es heißt loslassen.',
    E'Herr, hilf mir, zu vergeben. Ich kann es nicht aus mir heraus. Gib mir deine Vergebungskraft. Amen.',
    E'Nenne eine Person, der du vergeben willst. Bete das Vaterunser für sie.',
    '[]'::jsonb),
  ((select id from program), 24,
    'Jak 4,6',
    E'Gott widersteht den Hochmütigen, den Demütigen aber schenkt er seine Gnade.',
    E'Die Wurzel vieler Fälle ist Stolz: "Mir passiert das nicht mehr." Demut rechnet mit der eigenen Schwäche — und bittet täglich.',
    E'Herr, ich bin schwach. Ohne dich kann ich nichts. Mit dir alles. Amen.',
    E'Sage heute dreimal ehrlich: "Ohne Christus kann ich nichts." (Vgl. Joh 15,5)',
    '[]'::jsonb),
  ((select id from program), 25,
    'Mt 18,10',
    E'Hütet euch davor, einen von diesen Kleinen zu verachten! Denn ich sage euch: Ihre Engel im Himmel schauen stets das Angesicht meines himmlischen Vaters.',
    E'Pornografie zerstört nicht nur dich — sie verletzt den ganzen Leib Christi. Denke an die, die in der Industrie ausgebeutet werden.',
    E'Herr, erbarme dich der Opfer. Heile, was Menschen einander antun. Befreie, was gebunden ist. Amen.',
    E'Bete heute für die Menschen in der Pornoindustrie. Spende, wenn möglich, an eine Organisation gegen Menschenhandel.',
    '[]'::jsonb),
  ((select id from program), 26,
    '1 Joh 2,16',
    E'Denn das alles, was in der Welt ist, die Begierde des Fleisches, die Begierde der Augen und das Prahlen mit dem Besitz — es kommt nicht vom Vater, sondern von der Welt.',
    E'Die Augenlust ist eine der drei großen Wunden. Sie zu benennen, ist der erste Schritt.',
    E'Herr, reinige meine Augen. Was ich sehe, forme mich. Lass mich Schönes sehen — das, was zu dir führt. Amen.',
    E'Gehe heute in die Natur. 20 Minuten. Nur schauen. Kein Handy.',
    '[]'::jsonb),
  ((select id from program), 27,
    'Joh 8,32',
    E'Ihr werdet die Wahrheit erkennen und die Wahrheit wird euch frei machen.',
    E'Pornografie lügt. Sie lügt über Frauen, über Männer, über Liebe, über dich selbst. Die Wahrheit Christi macht frei.',
    E'Herr, du bist die Wahrheit. Befreie mich von jeder Lüge, die in mir wohnt. Amen.',
    E'Notiere: Welche Lügen hat mir die Pornografie eingeredet? Zerreiße den Zettel danach.',
    '[]'::jsonb),
  ((select id from program), 28,
    'Röm 8,37',
    E'Doch all das überwinden wir durch den, der uns geliebt hat.',
    E'Vier Wochen. Du hast nicht gesiegt — Christus siegt in dir.',
    E'Herr, du siegst. Ich darf in deinem Sieg stehen. Danke. Amen.',
    E'Schreibe einen Dankesbrief an Gott. Eine halbe Seite.',
    '[]'::jsonb),
  ((select id from program), 29,
    'Ps 91,11',
    E'Denn er befiehlt seinen Engeln, dich zu behüten auf all deinen Wegen.',
    E'Du hast einen Schutzengel. Er ist dir näher, als du denkst. Rufe ihn an.',
    E'Heiliger Schutzengel, den Gott mir gegeben hat: erleuchte, beschirme, leite und führe mich. Amen.',
    E'Rede heute konkret mit deinem Schutzengel — bitte ihn, bei Versuchungen sofort dazwischenzutreten.',
    '[]'::jsonb),
  ((select id from program), 30,
    'Eph 4,22-24',
    E'Legt den alten Menschen ab… werdet neu in eurem Geist und Denken und zieht den neuen Menschen an.',
    E'Eine Sucht lässt sich nicht nur weglassen. Sie muss ersetzt werden. Was tust du stattdessen?',
    E'Herr, zeige mir gute Gewohnheiten. Fülle die Leerstelle mit Gutem. Amen.',
    E'Definiere eine neue Gewohnheit: Wenn die Versuchung kommt — was tue ich stattdessen? (z.B. Psalm beten, Liegestütze, Kaltduschen, Rosenkranz.)',
    '[]'::jsonb),
  ((select id from program), 31,
    'Lk 15,20',
    E'Der Vater sah ihn schon von Weitem kommen und er hatte Mitleid mit ihm. Er lief dem Sohn entgegen.',
    E'Der Vater läuft. Er steht nicht abwartend. Er läuft dir entgegen.',
    E'Vater, ich komme nach Hause. Ich verdiene es nicht. Und du läufst mir entgegen. Amen.',
    E'Lies heute das ganze Gleichnis Lk 15,11-32 langsam.',
    '[]'::jsonb),
  ((select id from program), 32,
    'Röm 2,15',
    E'… das Gesetz ist in ihre Herzen geschrieben, ihr Gewissen legt Zeugnis davon ab.',
    E'Ein wundes Gewissen stumpft ab. Ein gebetetes Gewissen wird wieder feinfühlig. Dein Gewissen heilt mit dir.',
    E'Heiliger Geist, schärfe mein Gewissen. Zeige mir, was dir missfällt — in kleinen und großen Dingen. Amen.',
    E'Mache heute Abend eine Gewissenserforschung — 5 Minuten, ehrlich.',
    '[]'::jsonb),
  ((select id from program), 33,
    '1 Thess 4,3',
    E'Das ist es, was Gott will: eure Heiligung. Dass ihr die Unzucht meidet.',
    E'Keuschheit ist keine Abwesenheit. Keuschheit ist eine positive Tugend — die geordnete, würdige Liebe.',
    E'Herr, schenke mir die Tugend der Keuschheit — nicht als Verbot, sondern als Freiheit. Amen.',
    E'Lies heute KKK 2337-2347 zum Thema Keuschheit.',
    '[]'::jsonb),
  ((select id from program), 34,
    'Ps 27,4',
    E'Eines erbitte ich vom Herrn, danach verlangt mich: im Haus des Herrn zu wohnen alle Tage meines Lebens, die Freundlichkeit des Herrn zu schauen.',
    E'Gott ist schön. Wahre Schönheit heilt den Blick. Suche das wirklich Schöne — Kunst, Musik, Natur, Liturgie.',
    E'Herr, du Schöner. Lass mich dich schauen. Dann heilen die Augen. Amen.',
    E'Höre heute 20 Minuten sakrale Musik (Palestrina, Gregorianik, Arvo Pärt). Ohne Nebentätigkeit.',
    '[]'::jsonb),
  ((select id from program), 35,
    'Eph 5,31-32',
    E'Darum wird der Mann Vater und Mutter verlassen und sich an seine Frau binden und die zwei werden ein Fleisch sein. Dies ist ein tiefes Geheimnis; ich beziehe es auf Christus und die Kirche.',
    E'Die geschlechtliche Liebe ist Ikone der Liebe Christi zur Kirche. Pornografie zerreißt diese Ikone. Heilung bedeutet: die Ikone wiederherstellen.',
    E'Herr, heile mein Bild von Liebe, Ehe und Geschlechtlichkeit. Lass mich in allem deine Liebe zur Kirche sehen. Amen.',
    E'Bete heute für alle Ehepaare — besonders jene, deren Ehe durch Pornografie verwundet ist.',
    '[]'::jsonb),
  ((select id from program), 36,
    '1 Petr 5,8',
    E'Seid nüchtern und wachsam! Euer Widersacher, der Teufel, geht wie ein brüllender Löwe umher und sucht, wen er verschlingen kann.',
    E'Der Kampf endet nicht mit Tag 40. Die Wachsamkeit beginnt dort erst richtig.',
    E'Herr, mache mich wachsam. Der Feind lauert. Aber du bist stärker. Amen.',
    E'Plane konkret: Was tust du ab Tag 41? Welches tägliche Gebet? Welche Struktur?',
    '[]'::jsonb),
  ((select id from program), 37,
    'Koh 4,9-10',
    E'Zwei sind besser als einer. Denn falls sie fallen, richtet einer den anderen auf. Doch wehe dem, der allein ist und dann fällt.',
    E'Keiner besiegt diese Sucht allein. Du brauchst einen Bruder, einen Beichtvater, eine Gruppe.',
    E'Herr, führe mir einen Weggefährten zu. Einen, der versteht. Der mit mir kämpft. Amen.',
    E'Sprich heute mit einer vertrauten Person über deinen Kampf. Nicht alles — aber etwas.',
    '[]'::jsonb),
  ((select id from program), 38,
    '1 Kor 15,43',
    E'Gesät wird in Unehre, auferweckt in Herrlichkeit; gesät wird in Schwachheit, auferweckt in Stärke.',
    E'Dein Leib ist zur Auferstehung bestimmt. Die Unreinheit ist vorläufig. Die Herrlichkeit ist ewig.',
    E'Herr, der du meinen Leib auferwecken wirst: heilige ihn jetzt schon, damit er einst in Herrlichkeit auferstehen kann. Amen.',
    E'Bekenne heute laut das Glaubensbekenntnis — besonders: "die Auferstehung der Toten."',
    '[]'::jsonb),
  ((select id from program), 39,
    '2 Tim 1,7',
    E'Denn Gott hat uns nicht einen Geist der Verzagtheit gegeben, sondern den Geist der Kraft, der Liebe und der Besonnenheit.',
    E'Die Angst, wieder zu fallen, ist selbst eine Versuchung. Vertraue. Gott ist größer.',
    E'Herr, ich gebe dir meine Angst. Ich vertraue auf deine Kraft. Du hältst mich. Amen.',
    E'Schreibe deine Ängste auf. Verbrenne oder zerreiße den Zettel. Gott hat sie genommen.',
    '[]'::jsonb),
  ((select id from program), 40,
    'Lk 4,13-14',
    E'Nachdem der Teufel alle Versuchungen beendet hatte, ließ er von ihm ab, bis zur gegebenen Zeit. Jesus kehrte, erfüllt von der Kraft des Geistes, nach Galiläa zurück.',
    E'Jesus verließ die Wüste in der Kraft des Geistes. Du verlässt sie heute ebenso. Nicht als Sieger deiner Kraft — als Empfänger seiner.',
    E'Herr, vierzig Tage. Du warst bei mir. Ich bin nicht, wer ich war. Schick mich zurück in den Alltag — erfüllt von deinem Geist. Amen.',
    E'Gehe heute zur heiligen Messe und empfange bewusst die Kommunion. Danke für die Gnade dieser vierzig Tage. Plane den Weg weiter — Tag 41 ist morgen.',
    '[]'::jsonb)
on conflict (program_id, day_number) do update set
  scripture_ref = excluded.scripture_ref,
  scripture_de = excluded.scripture_de,
  reflection_de = excluded.reflection_de,
  prayer_de = excluded.prayer_de,
  action_de = excluded.action_de;

-- ---------------------------------------------------------------------------
-- Weg 2: Aufbruch — 20 Tage
-- ---------------------------------------------------------------------------

insert into healing_programs (
  slug, theme, duration_days, title_de, title_en,
  subtitle_de, intro_de, scripture_motto, closing_de,
  requires_confessor, show_seelengemeinschaft, icon, is_published
) values (
  'aufbruch-20-tage',
  'acedia',
  20,
  'Aufbruch',
  'Departure',
  '20 Tage gegen die Trägheit',
  E'Faulheit ist mehr als "nicht aufstehen wollen". Die klassische Tradition nennt sie Acedia — den "Mittagsdämon" (Ps 91,6), den Widerwillen gegen das Gute, die Ermüdung an Gott und den Pflichten des Lebens. Sie äußert sich als Prokrastination, Handy-Scroll, Streaming-Stunden, Leere nach dem Erwachen.\n\nDieser Weg ist kein Produktivitäts-Kurs. Er heilt die Wurzel: die Liebe zu Gott und zum Leben wiederzufinden, damit das Tun wieder aus Liebe kommt — nicht aus Zwang.\n\nEmpfohlene Begleitung:\n- Feste Aufstehzeit und feste Bettzeit\n- Ein einfacher Tagesplan (handgeschrieben, nicht digital)\n- Eine tägliche Gebetszeit — am besten morgens',
  E'1 Kön 19,7 — "Steh auf und iss! Sonst ist der Weg zu weit für dich."',
  E'Ab Tag 21:\n- Morgenregel: Aufstehen, Kreuzzeichen, 5 Minuten Gebet, Tagesplan.\n- Abendregel: Gewissenserforschung, Dankbarkeit, Bettzeit.\n- Wochenregel: Sonntagsmesse, ein ganzer Tag ohne Bildschirm, ein Treffen mit Freunden.\n- Monatsregel: Beichte, ein Tag Einkehr, eine neue kleine Herausforderung.\n\nDie Acedia kehrt wieder — wie der Mittagsdämon täglich neu erscheint. Aber sie hat keine Macht über den, der wacht, betet und arbeitet.\n\n"Bete und arbeite — das eine trägt das andere."\n— Hl. Benedikt von Nursia',
  false,
  false,
  'bolt',
  true
)
on conflict (slug) do update set
  theme = excluded.theme,
  duration_days = excluded.duration_days,
  title_de = excluded.title_de,
  title_en = excluded.title_en,
  subtitle_de = excluded.subtitle_de,
  intro_de = excluded.intro_de,
  scripture_motto = excluded.scripture_motto,
  closing_de = excluded.closing_de,
  requires_confessor = excluded.requires_confessor,
  show_seelengemeinschaft = excluded.show_seelengemeinschaft,
  icon = excluded.icon,
  is_published = excluded.is_published,
  updated_at = now();

-- Days 1-20 for Weg 2
with program as (select id from healing_programs where slug = 'aufbruch-20-tage')
insert into healing_program_days (
  program_id, day_number, scripture_ref, scripture_de,
  reflection_de, prayer_de, action_de, prayer_refs
) values
  ((select id from program), 1,
    'Ps 91,5-6',
    E'Du brauchst dich vor dem Schrecken der Nacht nicht zu fürchten… nicht vor der Seuche, die im Finstern schleicht, vor der Pest, die wütet am Mittag.',
    E'Die Kirchenväter nannten die Faulheit den "Mittagsdämon" — er schlägt zu, wenn der erste Schwung vorbei ist, lange vor dem Feierabend. Erkenne ihn heute.',
    E'Herr, ich erkenne den Feind meiner Trägheit. Er hat einen Namen. Er ist nicht stärker als du. Amen.',
    E'Stehe heute 15 Minuten früher auf als gewohnt. Kein Snooze.',
    '[]'::jsonb),
  ((select id from program), 2,
    '1 Kön 19,5-7',
    E'Ein Engel rührte ihn an und sprach: Steh auf und iss!… Der Engel des Herrn kam zum zweiten Mal, rührte ihn an und sprach: Steh auf und iss! Sonst ist der Weg zu weit für dich.',
    E'Elija wollte sterben. Gott schickte ihm nicht eine Predigt — Gott schickte Brot und den Befehl: "Steh auf." Der Weg ist noch weit.',
    E'Herr, ich bin müde. Ich stehe auf, weil du es sagst. Sonst ist der Weg zu weit für mich. Amen.',
    E'Iss heute ein Frühstück — auch wenn du keinen Hunger hast. Der Leib ist Teil des geistlichen Kampfes.',
    '[]'::jsonb),
  ((select id from program), 3,
    'Ps 63,2',
    E'Gott, du mein Gott, dich suche ich, meine Seele dürstet nach dir.',
    E'Die ersten Minuten des Tages gehören dem, den du zuerst suchst. Handy oder Gott — du entscheidest.',
    E'Herr, meine ersten Gedanken gehören dir. Morgens, wenn ich aufwache, bist du schon da. Amen.',
    E'Lass heute dein Handy morgens 30 Minuten aus. Stattdessen: 5 Minuten Gebet, 5 Minuten Wasser trinken und anziehen, 20 Minuten Tag beginnen.',
    '[]'::jsonb),
  ((select id from program), 4,
    'Lk 10,41-42',
    E'Marta, Marta, du machst dir Sorgen und Unruhe um vieles, aber nur eines ist notwendig.',
    E'Faulheit und Zerstreuung sind Schwestern. Wer alles gleichzeitig tun will, tut am Ende nichts. Eines ist notwendig.',
    E'Herr, zeige mir heute das Eine. Lass mich nicht im Vielerlei versinken. Amen.',
    E'Schreibe heute morgens drei Aufgaben auf. Nur drei. Tu die wichtigste zuerst.',
    '[]'::jsonb),
  ((select id from program), 5,
    'Spr 6,9-10',
    E'Wie lange, du Fauler, willst du noch daliegen? Wann willst du aufstehen aus dem Schlaf? Noch ein wenig Schlaf, noch ein wenig Schlummer, noch ein wenig die Hände ineinanderlegen, um auszuruhen.',
    E'Die Schrift spricht deutlich. Erkenne, wo du "nur noch ein wenig" sagst.',
    E'Herr, heile mein "noch ein wenig". Lass mich ehrlich sein, wo ich vermeide. Amen.',
    E'Notiere heute Abend: Wo habe ich heute prokrastiniert? Was hat es mir gekostet?',
    '[]'::jsonb),
  ((select id from program), 6,
    'Neh 8,10',
    E'Die Freude am Herrn ist eure Stärke.',
    E'Acedia ist die Unfähigkeit, sich an Gott zu freuen. Die Heilung beginnt damit, eine echte Freude zu finden — und sie wieder mit Gott zu verbinden.',
    E'Herr, meine Freude. Schenke mir wieder Freude — am Tag, am Leben, an dir. Amen.',
    E'Tue heute bewusst eine Sache, die dich freut. Danke Gott laut dafür.',
    '[]'::jsonb),
  ((select id from program), 7,
    'Mk 2,27',
    E'Der Sabbat ist für den Menschen da, nicht der Mensch für den Sabbat.',
    E'Gott will keinen erschöpften Menschen. Ruhe gehört zum Leben. Aber Ruhe ist nicht dasselbe wie Dauererschöpfung.',
    E'Herr, lehre mich, richtig zu ruhen. Nicht aus Flucht — aus Vertrauen. Amen.',
    E'Nimm dir heute eine bewusste Ruhezeit: 30 Minuten ohne Bildschirm, ohne Aufgabe. Nur Dasein.',
    '[]'::jsonb),
  ((select id from program), 8,
    'Lk 16,10',
    E'Wer in den kleinsten Dingen zuverlässig ist, der ist auch in den großen zuverlässig.',
    E'Heiligkeit ist nicht im Außergewöhnlichen — sie ist in der getanen Pflicht des heutigen Tages.',
    E'Herr, die Pflicht des heutigen Tages ist mein Weg zu dir. Lass mich sie nicht verachten. Amen.',
    E'Erledige heute eine Aufgabe, die du schon länger aufschiebst. Eine — aber vollständig.',
    '[]'::jsonb),
  ((select id from program), 9,
    'Koh 9,10',
    E'Alles, was deine Hand zu tun vorfindet, das tu mit der Kraft, die du hast.',
    E'Ein ungemachtes Bett ist ein kleines Bild der Acedia. Ein gemachtes Bett ist ein kleines Zeichen der Ordnung.',
    E'Herr, die kleinen Dinge. Lass sie mir wichtig werden. Sie sind nicht klein. Amen.',
    E'Mache heute dein Bett. Räume einen Tisch auf. Kehre einen Raum. Diene der Ordnung um dich.',
    '[]'::jsonb),
  ((select id from program), 10,
    'Gal 6,9',
    E'Lasst uns nicht müde werden, das Gute zu tun; denn wir werden ernten, wenn wir nicht nachlassen.',
    E'Zehn Tage. Die Hälfte. Müde werden ist menschlich — nachlassen ist eine Entscheidung.',
    E'Herr, ich werde müde. Aber ich lasse nicht nach. Ich ernte, was du gesät hast. Amen.',
    E'Schreibe auf: Was hat sich in zehn Tagen verändert? Notiere drei konkrete Dinge.',
    '[]'::jsonb),
  ((select id from program), 11,
    '1 Kor 6,12',
    E'Alles ist mir erlaubt — aber nicht alles nützt mir. Alles ist mir erlaubt — aber nichts soll mich beherrschen.',
    E'Das Handy ist nicht das Problem. Beherrscht-Werden ist das Problem. Prüfe, wer herrscht.',
    E'Herr, nichts soll mich beherrschen außer dir. Befreie mich vom Scrollen. Amen.',
    E'Setze heute für eine App (Instagram, YouTube, TikTok…) eine Zeitbegrenzung: maximal 15 Minuten.',
    '[]'::jsonb),
  ((select id from program), 12,
    'Kol 3,23',
    E'Bei allem, was ihr tut, arbeitet von Herzen, als würdet ihr für den Herrn arbeiten, nicht für die Menschen.',
    E'"Ora et labora" — beten und arbeiten — ist keine Zweiteilung. Die Arbeit selbst kann Gebet werden.',
    E'Herr, meine Arbeit heute sei dir geweiht. Was ich tue, tue ich für dich. Amen.',
    E'Widme jede größere Aufgabe heute mit einem Stoßgebet: "Herr, für dich."',
    '[]'::jsonb),
  ((select id from program), 13,
    'Joh 10,10',
    E'Ich bin gekommen, damit sie das Leben haben und es in Fülle haben.',
    E'Acedia ist Lebensmüdigkeit. Christus kam, damit du lebst — in Fülle. Das Evangelium ist frohe Botschaft.',
    E'Herr, schenke mir Lebenslust — deine, nicht meine. Fülle, die aus dir kommt. Amen.',
    E'Tue heute etwas Lebendiges: Musik hören und dich bewegen, kochen, einen Menschen treffen. Kein Bildschirm.',
    '[]'::jsonb),
  ((select id from program), 14,
    '1 Kor 9,27',
    E'Vielmehr züchtige ich meinen Leib und mache ihn zu meinem Sklaven, damit ich nicht anderen predige und selber verwerflich werde.',
    E'Der Leib folgt dem Willen — wenn der Wille trainiert ist. Trägheit im Leib wird zu Trägheit im Geist.',
    E'Herr, der Leib ist dein Geschenk. Lass mich ihn bewegen, stärken, ehren. Amen.',
    E'Bewege dich heute 30 Minuten. Gehen, Laufen, Fahrradfahren, Sport. Jetzt — nicht morgen.',
    '[]'::jsonb),
  ((select id from program), 15,
    'Hebr 10,24-25',
    E'Lasst uns aufeinander achten und uns zur Liebe und zu guten Taten anspornen.',
    E'Trägheit isoliert. Gemeinschaft heilt. Du bist nicht allein unterwegs.',
    E'Herr, schenke mir Menschen, die mich antreiben — zum Guten. Und lass mich andere antreiben. Amen.',
    E'Ruf heute einen Menschen an, mit dem du länger nicht gesprochen hast. Vereinbare ein Treffen.',
    '[]'::jsonb),
  ((select id from program), 16,
    'Mt 11,30',
    E'Denn mein Joch drückt nicht und meine Last ist leicht.',
    E'Die Mönchsväter sagten: "Habe eine kleine Regel und halte sie." Nicht perfekt — aber treu.',
    E'Herr, gib mir eine einfache Regel. Eine, die ich halten kann. Die mich hält. Amen.',
    E'Schreibe deine persönliche Tagesregel auf — 3 bis 5 Punkte. Morgens, mittags, abends. Nicht mehr.',
    '[]'::jsonb),
  ((select id from program), 17,
    '1 Thess 5,18',
    E'Dankt für alles; denn das ist der Wille Gottes für euch in Christus Jesus.',
    E'Dankbarkeit ist das Gegenteil von Acedia. Wer dankt, sieht das Gute. Wer das Gute sieht, will es tun.',
    E'Herr, danke. Für den Tag, den Atem, die Menschen, das Brot. Danke. Amen.',
    E'Schreibe heute Abend 10 Dinge auf, für die du dankbar bist. Konkret, nicht allgemein.',
    '[]'::jsonb),
  ((select id from program), 18,
    'Lk 9,62',
    E'Keiner, der die Hand an den Pflug gelegt hat und nochmals zurückblickt, taugt für das Reich Gottes.',
    E'Der heilige Benedikt nannte es stabilitas — das Bleiben. Nicht wegfliehen vor Routine, Arbeit, Verpflichtung.',
    E'Herr, lass mich bleiben. Nicht ausweichen. Nicht fliehen. Bei dir, bei meiner Arbeit, bei meinen Menschen. Amen.',
    E'Identifiziere heute, wovor du fliehst. Gehe einen Schritt darauf zu — heute, jetzt.',
    '[]'::jsonb),
  ((select id from program), 19,
    'Hebr 12,2',
    E'Lasst uns aufschauen zu Jesus, dem Urheber und Vollender des Glaubens.',
    E'Wer nach unten schaut, stolpert. Wer aufschaut, geht. Die Vision zieht dich.',
    E'Herr, lass mich aufschauen. Nicht auf mich — auf dich. Du ziehst, ich folge. Amen.',
    E'Formuliere heute: Was ist deine Vision für die nächsten 6 Monate? Ein Satz. Schreib ihn hin, wo du ihn täglich siehst.',
    '[]'::jsonb),
  ((select id from program), 20,
    'Phil 3,13-14',
    E'Eines aber tue ich: Ich vergesse, was hinter mir liegt, und strecke mich nach dem aus, was vor mir ist. Das Ziel vor Augen, jage ich nach dem Siegespreis.',
    E'Zwanzig Tage. Der Weg geht weiter. Du bist in Bewegung. Das ist das Gegenteil von Acedia.',
    E'Herr, du hast mich in Bewegung gebracht. Ich strecke mich nach dem aus, was vor mir ist. Amen.',
    E'Gehe heute zur heiligen Messe und danke. Lege eine konkrete Regel für die nächsten 40 Tage fest: welches Gebet, welche Gewohnheit, welche Grenze?',
    '[]'::jsonb)
on conflict (program_id, day_number) do update set
  scripture_ref = excluded.scripture_ref,
  scripture_de = excluded.scripture_de,
  reflection_de = excluded.reflection_de,
  prayer_de = excluded.prayer_de,
  action_de = excluded.action_de;
